In [1]:
from pybullet_suite import *

pybullet build time: May 20 2022 19:44:17


In [ ]:
world = BulletWorld(gui=True)
sm = BulletSceneMaker(world)

In [3]:
panda = world.load_robot(Panda, "panda")

In [6]:
qtn = np.array([ 7.0178336e-01, -3.9567790e-04,  4.4768292e-01,  5.5414802e-01])
frame = Pose(Rotation.from_quat(qtn), trans=[0.6, 0., 0.4])

In [7]:
sm.view_frame(frame)

In [9]:
q = panda.inverse_kinematics(pose=frame, start_central=False)

In [11]:
jac = panda.get_jacobian(q)

In [13]:
np.sqrt(np.linalg.det(jac@jac.T))

0.08914658593807591

In [14]:
panda.set_joint_angles(q)

In [18]:
panda.get_ee_pose().trans

array([6.00268733e-01, 9.93339288e-05, 3.99960924e-01])

In [17]:
panda.get_ee_pose().rot.as_matrix()

array([[ 0.59918842, -0.49674242,  0.62786958],
       [ 0.49558149, -0.3858036 , -0.77817387],
       [ 0.62878631,  0.77743331,  0.0150073 ]])

In [16]:
pand

array([ 0.18621988,  0.02782874,  0.10730047, -2.2581845 , -1.84427497,
        1.84645773,  2.22105255])